version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: x86
environment:
  debug: 1
before_build:
- cmd: nuget restore
build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
after_test:
- cmd: >-
    cd GameLauncher\bin\x86\Release\

    7z a -tzip GameLauncher-portable-prerelease.zip GameLauncher.exe *.dll
artifacts:
- path: GameLauncher\bin\x86\Release\GameLauncher-portable-prerelease.zip
  name: zipfile
  type: WebDeployPackage
deploy:
- provider: GitHub
  tag: currentBuild
  release: currentBuild
  auth_token:
    secure: YQ0yLUpQzV+Umtp1eD0mxhZeR+1OE4c6jgI8Lr0HMHALzeSPRdLYYAa5SewLjPg6
  artifact: zipfile
  prerelease: true
  force_update: true